export enum UserRole { CUSTOMER = 'CUSTOMER', RESTAURANT_OWNER = 'RESTAURANT_OWNER', ADMIN = 'ADMIN' }
export enum OrderStatus { PENDING = 'PENDING', CONFIRMED = 'CONFIRMED', PREPARING = 'PREPARING', DELIVERING = 'DELIVERING', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED' }
