export enum UserRole { CUSTOMER = 'CUSTOMER', RESTAURANT_OWNER = 'RESTAURANT_OWNER', ADMIN = 'ADMIN' }
export enum OrderStatus { PENDING = 'PENDING', CONFIRMED = 'CONFIRMED', PREPARING = 'PREPARING', DELIVERING = 'DELIVERING', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED' }
export enum PaymentMethod { COD = 'COD', MOMO = 'MOMO', VNPAY = 'VNPAY', BANK_TRANSFER = 'BANK_TRANSFER', CARD = 'CARD' }
export enum PaymentStatus { UNPAID = 'UNPAID', PAID = 'PAID', FAILED = 'FAILED', REFUNDED = 'REFUNDED' }
